Replace Rally API call with hard-coded value (GAUD-5065)

diff --git a/get-lms-release/action.yml b/get-lms-release/action.yml
--- a/get-lms-release/action.yml
+++ b/get-lms-release/action.yml
@@ -1,31 +1,29 @@
 name: 'Get LMS Version'
-description: 'Retrieves the current dev version of Brightspace from Rally'
+description: 'Retrieves the current active development version of Brightspace'
 inputs:
   RALLY_API_KEY:
     description: 'Token to find active releases in Rally'
     required: true
 outputs:
   LMS_VERSION:
-    description: 'Current dev version of the LMS'
+    description: 'Current active development version of the LMS'
     value: ${{ steps.get-lms-version.outputs.version }}
 
 runs:
   using: composite
   steps:
-    - name: Install Dependencies
-      run: |
-        echo "Installing dependencies..."
-        npm install chalk@5 moment-timezone@0.5 rally@2 --prefix ${{ github.action_path }} --no-save --loglevel error
-      shell: bash
-
     - name: Get LMS Version
       id: get-lms-version
-      uses: actions/github-script@v6
+      run: |
+        VERSION="20.24.3"
+        if [ ${RALLY_API_KEY} != "" ]; then
+          echo "RALLY_API_KEY detected, returning hard-coded release version..."
+        else
+          echo "RALLY_API_KEY is required, failing..."
+          exit 1
+        fi
+        echo "$VERSION is the active development release."
+        echo "version=$VERSION" >> $GITHUB_OUTPUT
+      shell: bash
       env:
-        FORCE_COLOR: 3
         RALLY_API_KEY: ${{ inputs.RALLY_API_KEY }}
-      with:
-        script: |
-          console.log('Getting LMS Version...');
-          const { default: run } = await import('${{ github.action_path }}/index.js');
-          await run(core);
